name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Modrinth
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}

      - name: Set version from release tag
        run: |
          sed -i "s/^mod_version=.*/mod_version=${{ github.event.release.tag_name }}/" gradle.properties

      - name: Build the mod
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@2.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ secrets.MODRINTH_PROJECT_ID }}
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            fabric
          game-versions: |-
            1.21.1
          files: |
            build/libs/gommemode-${{ github.event.release.tag_name }}.jar
