name: GitHub Release draft

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: gradle-cache-${{ runner.os }}

      - run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-6)" >> $GITHUB_ENV

      - run: sed -i "s/^mod_version=.*/mod_version=${{ env.SHORT_SHA }}/" gradle.properties

      - run: ./gradlew build

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release Draft and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/gommemode-${{ env.SHORT_SHA }}.jar
          draft: true
          prerelease: true
          tag_name: ${{ env.SHORT_SHA }}
          release_name: "Release ${{ env.SHORT_SHA }}"
          body: ${{ steps.changelog.outputs.changes }}