name: GitHub Release draft

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: gradle-cache-${{ runner.os }}

      - name: Extract things
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-6)" >> $GITHUB_ENV
          echo "MINECRAFT_VERSION=$(grep 'minecraft_version' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Update gradle.properties with SHORT_SHA
        run: |
          sed -i "s/^version=.*/version=${{ env.MINECRAFT_VERSION }}-${{ env.SHORT_SHA }}/" gradle.properties
          cat gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create changelogs
        id: changelog
        uses: heineiuo/create-changelogs@master

      - name: Create Release Draft and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          draft: true
          prerelease: true
          tag_name: ${{ env.MINECRAFT_VERSION }}-${{ env.SHORT_SHA }}
          name: "${{ env.MINECRAFT_VERSION }} - ${{ env.SHORT_SHA }} - ${{ env.BRANCH_NAME }}"
          body: ${{ steps.changelog.outputs.changelogs }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}