name: GitHub Release draft

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: gradle-cache-${{ runner.os }}

      - run: sed -i "s/^mod_version=.*/mod_version=${{ github.sha }}/" gradle.properties

      - run: ./gradlew build

      - name: Create Release Draft and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/gommemode-${{ github.sha }}.jar
          draft: true
          prerelease: true